ciemss/pyciemss

src/pyciemss/PetriNetODE/interfaces.py

Adds docstrings to TA4 interfaces describing arguments and returns.

Add detailed docstrings for TA4 interfaces

---

setup.cfg

Change setup to fix MIRA name error

---

setup.cfg

* changed mira version before bug
* fix error

Change setup to fix MIRA name error (#205)

---

src/pyciemss/PetriNetODE/interfaces.py
src/pyciemss/custom_decorators.py

**About**: A new decorator that will log out the function name and doc string when an error occurs within that function. Designed to help with debugging to quickly find where the code is breaking.
**Use**: You can decorate any function. For nested functions the logging will print the function name and docs for every decorated level that are impacted by the error.
*I put the decorator on all the functions I thought might benefit from this but not exactly sure if I covered all the correct ones.

Decorator logging function

---

src/pyciemss/PetriNetODE/interfaces.py

#232 was developed at the same time as, but separately from #204. This PR adds the contribution of #232 to the endpoint added in #204.

Added pyciemss logging wrapper to optimize endpoint

---

src/pyciemss/Ensemble/interfaces.py
src/pyciemss/PetriNetODE/interfaces.py

updated pseudocount definition to mention adding uncertainty to observations instead of model parameters

Updating definition of pseudocount

---

.gitignore
src/pyciemss/PetriNetODE/interfaces.py
test/test_petrinet_ode/test_ode_interfaces.py

We simply add an infinitesimal amount of noise to the time and intervention and/or observation is applied.

Addressed time collision errors with logging, interventions, and observations

---

setup.cfg

Bump MIRA to use the most recent version

---

notebook/hackathon_prep/scenario3_abm.ipynb
notebook/july_evaluation/Scenario_2a.ipynb
notebook/july_evaluation/Scenario_2b.ipynb
notebook/july_evaluation/Scenario_2c.ipynb

These notebooks only have instructions, and leave placeholder cells for code.

Eval 2023/07 Scenario 2

---

src/pyciemss/utils/AMR_utils.py

Cleaning up the code, move utils file to correct directory

Add AMR_utils file to correct utils directory

---

notebook/ensemble_eval_sa/ensemble_results/Untitled.ipynb
notebook/july_evaluation/Vega_Plot_Issue317.ipynb
src/pyciemss/visuals/trajectories.vg.json
test/test_visuals/test_schemas.py

Updated trajectories schema, the exemplar points were pointing at un-faceted data. Added test to catch this on future schemas.

317 odd behavior when plotting data

---

.github/workflows/main.yml

Create GitHub actions TA4 integration workflow

---

src/pyciemss/PetriNetODE/interfaces.py

- Additional key "inferred_parameters" for result returned from `load_and_calibrate_and_optimize_and_sample_petri_model`
- Updated documentation for returned dictionary to include the above

Updated TA4 interfaces to return inferred parameters for OUU

---

setup.cfg

Bump pyciemss version

---

notebook/evaluation/scenario1.ipynb

Edited and added explainer text to 6-month evaluation scenario 1 notebook. Note that this notebook is not accessible on main, and as far as I can tell is only accessible through branch 56.
Closes #62

62 add explainer text to evaluation scenario 1

---

notebook/evaluation/scenario3.ipynb

There was no code in this notebook, as far as I can tell it is just the text of the ASKEM 6-mo eval scenario 3, so I just cleaned it up a little.
Close #64

nothing to do here

---

pyciemss/interfaces.py

This small PR adds `torch.nograd` context managers to prevent torch from propagating gradient information in interfaces that don't require it. This reduces the memory footprint and (may) improve performance slightly.

Block torch gradients for operations that don't require them

---

setup.cfg
tests/test_model_representations.py

Updating dependency to reflect updated inventory tool.
Updating tests to pytest.
More detailed failure reporting.
Checking additional models.

Re-introducing model_inventory-based tests

---

setup.cfg

Bump Mira to most recent tagged release.

Bump mira to 0.4.0

---

tests/visuals/test_schemas.py

Scaling test_threshold to 0.2. Addressing issue #481

 Jensen-Shannon score of 0.15 observed for some hardware choices.

---

pyciemss/integration_utils/result_processing.py

Pandas available in python 3.8 had different flags availabl.e

Different groupby structure to handle indexing 

---

setup.cfg

Mira just released 2 days ago. Let's stay up-to-date.

Bump mira to 0.5.0

---

pyciemss/interfaces.py
tests/test_interfaces.py

Ensemble calibrate

---

INSTALL.md

adding INSTALL.md

---

pyciemss/integration_utils/result_processing.py
tests/integration_utils/test_result_processing.py

* simplify intervention splicing
* lint
* removed test

Simplify interchange dictionary processing (#564)

---

pyciemss/interfaces.py
tests/fixtures.py

Fixed failing tests in `ac-ensemble-output`

---

setup.cfg

Bump Mira dependency to 0.7.0

---

.gitignore

added schema.vg.json and heatmap/ to gitignore
