- setup.cfg
This PR freezes the version of MIRA to the latest working version. This will ensure that any upstream changes to MIRA don't cause breaking changes to PyCIEMSS.
> Fix the MIRA version

- setup.cfg
**About**:  With the new changes the code expects a json file to be located in the src/pysiemss/visual folder. This file is in the repo but when you build the package the json files are not found so you get an error like this:
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/pyciemss/visuals/trajectories.vg.json'
`
With the new line in the setup.cfg file lets those files be included in the build.
> Allow json files to be included in dist package

- src/pyciemss/utils/interface_utils.py
- test/test_utils/test_interface_utils.py
Corrected `csv_to_list()` in `interface_utils.py` so that it now accepts missing entries. Unit test was added to `test_interface_utils.py`. 
Note: This branch replaces the older one for the same issue (this should be simpler with fewer changes/commits)
> 244 calibrate error when using nan entries 1

- src/pyciemss/PetriNetODE/interfaces.py
- test/test_petrinet_ode/test_ode_interfaces.py
This small PR adds a flag to our interface methods that triggers whether to run SVI with some subset of the parameters being calibrated deterministically.
Note: This implementation is made easy by the fact that variational inference with dirac-Delta distribution is exactly equivalent to MAP inference. We concatenate a autoguide using Pyro's `AutoGuideList` constructor.
> Provide an optional list of parameters to be calibrated deterministically

- setup.cfg
- src/pyciemss/PetriNetODE/interfaces.py
The user provides a 'progress hook' when calling a top-level operation. The hook is called by giving it a float representing the percentage of the job that has completed. Since a generic hook is used, the `pika` library and`job_id` no longer need to exist in PyCIEMSS
> Replace pika with progress hook

- pyciemss/mira_integration/compiled_dynamics.py
- tests/fixtures.py
This small PR ignores parameters that were previously placeholders, which caused a problem for the StockFlow example. In addition, we add back the StockFlow example to the test fixtures.
> Support StockFlow example

- .gitignore
- pyciemss/__init__.py
- setup.cfg
* Remove package finding AND add to module exports
* Clear out top-level `__init__.py`
* Reinclude explicit exports
* Include subpackages
* Skip incorrect lint error
* reorder imports for lint
* revert previous commit and add missing space before noqa
---------
> Remove package finding AND add to module exports (#407)

- .gitignore
- pyciemss/__init__.py
- pyciemss/integration_utils/result_processing.py
- pyciemss/interfaces.py
- setup.cfg
- tests/fixtures.py
- tests/test_interfaces.py
This PR adds basic output formatting to match the previous interface for TA4 integration.
> Add basic output formatting

- pyciemss/observation.py
- tests/fixtures.py
- tests/test_interfaces.py
This small PR primarily updates the models used in the test fixtures to include models with distributions on parameters, observables, and custom rate laws.
In the process of using these models, I discovered that the way we were generating noise using the default normal noise model was not scaled according to the state variable. This PR also corrects that, and modifies the noisy sampling test accordingly. This was necessary to get these new models to pass the tests.
> Update test fixtures to include new gold-standard AMRs

- pyciemss/compiled_dynamics.py
- pyciemss/integration_utils/result_processing.py
- pyciemss/interfaces.py
- pyciemss/mira_integration/compiled_dynamics.py
- pyciemss/observation.py
- tests/fixtures.py
- tests/test_interfaces.py
This PR adds `observables` to the output of the `sample` interface when it exists.
~~Note: this PR is currently blocked by not having any up-to-date AMRs that contain both observables, and numerically stable parameterizations.~~
~~blocked by #411 , as we'd like to add observables to ensemble models as well.~~
~~blocked by #415~~
> Add observables to sample output

- docs/source/interfaces.ipynb
- tests/fixtures.py
* updating urls for petri and stock flow example amrs
* Shortening url lengths to address linting issue
* Fixing urls for linting issue
* Changing AMR url in interfaces notebook
* Updating model_2_path to correct url
> updating urls for petri and stock flow example amrs (#419)

- docs/source/interfaces.ipynb
- pyciemss/compiled_dynamics.py
- pyciemss/ensemble/compiled_dynamics.py
- pyciemss/interfaces.py
- pyciemss/mira_integration/compiled_dynamics.py
- setup.cfg
- tests/fixtures.py
- tests/test_compiled_dynamics.py
- tests/test_ensemble_compiled_dynamics.py
This PR bumps ChiRho to use v0.2.0 and resolves any changes to the API that are necessary to accomplish this.
> Bump ChiRho version in dependencies and update any changes resulting from API changes

- tests/fixtures.py
This PR adds three regnet examples and deletes two petrinet and two stockflow amr example url to `fixtures.py`.
> Adding regnet urls to fixtures, and limiting number of examples to three per type

- pyciemss/compiled_dynamics.py
- pyciemss/interfaces.py
- tests/fixtures.py
- tests/test_interfaces.py
This PR adds parameter intervention to the `calibrate` interface, and refactors the interface tests to be more modular.
Here, adding an intervention to `calibrate` refers to the scenario where we are conditioning on data that was drawn from an interventional distribution. In other words, this is the continuous-time analog of how experimental data is incorporated into probabilistic inferences in this paper: https://arxiv.org/abs/1910.14124
> Add parameter interventions to calibrate and refactor interface tests

- pyciemss/interfaces.py
As discussed in #440 , it appears that the `pyciemss_logging_wrapper` decorator was previously omitted from the `calibrate` interface method. This tiny PR adds it back in.
> Add back pyciemss logging wrapper to calibrate

- pyciemss/interfaces.py
- tests/test_interfaces.py
This small PR addresses a comment in #444 by @fivegrant about how the progress hook for `calibrate` went missing after the refactoring PR in #431 . Here, we implement a progress hook by calling a user-provided function of the iteration id `i` and the `loss`, which the user can make stateful. In the tests we show an example of a progress hook that logs the iteration ids and losses, and stores them as an attribute.
> Add progress hook (and example usage in test) for `calibrate`

- pyciemss/interfaces.py
- pyciemss/mira_integration/compiled_dynamics.py
This small PR changes the behavior of `pyro.infer.Predictive` to batch multiple samples into a single vectorized ode solve. ChiRho does not currently support parallel sampling with dynamic interruptions. ChiRho does support parallel sampling with static interruptions, but I am running into some difficulty getting those to work with the compiled dynamics module. While this PR does not fully catch up to ChiRho's functionality (i.e. it misses parallel sampling with only static interventions), it still represents a substantial improvement.
Will address the missing functionality in a follow-up PR.
> Add parallel sampling when there are no interventions

- pyciemss/interfaces.py
- tests/test_calibrate_error_messages.py
- tests/test_interfaces.py
This PR adds an assert statement (see code below) in `calibrate` that will give the error message: "num_iterations must be a positive integer." if `num_iterations` is not a positive integer.
```python
assert isinstance(num_iterations, int) and num_iterations > 0, "num_iterations must be a positive integer."
```
Closes #456
> adding check for num_iterations in calibrate

- setup.cfg
@SamWitty this changes `setup.cfg` back to the way it was before I messed with it during the hackathon.
> Revert to old way of doing package discovery

- setup.cfg
This tiny PR pins pyro to 1.8.6. See https://github.com/BasisResearch/chirho/pull/523 and https://github.com/BasisResearch/chirho/pull/522 for additional discussion.
> Pin `pyro==1.8.6` to resolve upstream bugs in ChiRho

- pyciemss/integration_utils/result_processing.py
- pyciemss/interfaces.py
- pyciemss/visuals/trajectories.py
- tests/test_interfaces.py
In response to #500, restores the use of `time_unit` in creating the results dataframe from the integration interfaces.
Manually verified that the trajectories plot uses this for labeling, but did not test in an automated way.
> Restoring time-unit pass-through from interfaces.

- pyciemss/interfaces.py
- pyciemss/observation.py
- tests/test_interfaces.py
This PR adds observables to the `noise_model`, which can then be used to `calibrate` or `sample`.
To confirm that this fixes #492 , see that the CI fails after [3c3b3e7](https://github.com/ciemss/pyciemss/pull/517/commits/3c3b3e75cad68238e1b94b94f30328514b8422bf), which only uncomments a skipped test. After the fix in subsequent commits, the tests in the CI again pass.
Subsumes #516  .
> Fix calibrate to work on observables as well as state

- pyciemss/compiled_dynamics.py
This small PR adds a more informative error message than the one found buried deep with `TorchDiffEq`.
> Add more informative error if adaptive time step underflows

- pyciemss/integration_utils/result_processing.py
- tests/integration_utils/test_result_processing.py
Addressed this comment:
```python
```
With a regular expression 
```python
pattern = re.compile(f"(?:^|_){var}_(state|param)")
```
that captures the subtleties, and provided more rigorous test code that asserts `KeyError` is raised when no columns are found and `ValueError`  is raised when multiple columns are found.
> 556 pattern matching on var  finds multiple options

- pyciemss/integration_utils/result_processing.py
- tests/integration_utils/test_result_processing.py
This small PR removes some utilities that were previously used to splice in parameter interventions into the processed output. Previously, the utilities were agnostic to whether the intervention was on a state or a parameter. This is nice for its generality, but unfortunately caused some issues when there were multiple parameters that shared the same substring. See the last cell in this notebook for an example: https://github.com/ciemss/pyciemss/blob/ac-opt-fixedInterventions/docs/source/optimize_interface.ipynb
Fortunately, it turns out that splicing in the intervention values is only necessary for the interventions on parameters; interventions on states are already correctly reflected in the simulation output. Therefore, we can simply remove the state/parameter agnostic code, and …
> Simplify interchange dictionary processing

- tests/visuals/test_plots.py
See title. This addressed the failing tests locally, but I suggest running tests locally on review before merging into `ac-ensemble-output` as well.
> Resolved misalignment between `sample` and visualization tests

- pyciemss/mira_integration/compiled_dynamics.py
- tests/fixtures.py
addresses #578 
This small PR allows for observables to be defined in terms of (potentially random) parameters. This includes a minimal change to the definition of `eval_observables` to include parameters and manage parameter tensor shapes, as well as adding a relevant test.
> Add parameters to observables

- pyciemss/mira_integration/distributions.py
I modified [this file](https://github.com/ciemss/pyciemss/blob/672201f44752e40ed3a92a335ada136bc30f776e/pyciemss/mira_integration/distributions.py#L41) to add the required mapping between select probability distributions from [MIRA](https://github.com/gyorilab/mira/blob/65ff736eb63c13d72e3bb892f8f2488b086062ed/mira/dkg/resources/probonto.json#L903) and [their equivalents in PyTorch/Pyro](https://docs.pyro.ai/en/stable/distributions.html) .
> Add support for many more MIRA probonto distributions

- pyciemss/compiled_dynamics.py
- tests/fixtures.py
- tests/test_interfaces.py
This small PR fixes a bug found in #588 , in which interventions on constant parameters throws various output processing errors. This error occurred because the output processing was attempting to splice intervention assignments into a parameter that was never traced in Pyro, and thus never made its way to the logged output. The intervention was always correctly being applied (to the best of our knowledge), but errors occurred on output processing.
This PR addresses the problem by adding all deterministic parameters to the Pyro trace using `pyro.deterministic`.
This PR subsumes #594 , which introduced the test case.
closes #588
> Allow for interventions on constant parameters

- pyciemss/mira_integration/compiled_dynamics.py
- tests/fixtures.py
- tests/test_interfaces.py
This small PR addresses #567 and #599 by coercing all torch tensors to floats during compilation.
> Coerce AMR inputs to float

- tests/test_interfaces.py
Adding `test_observables_change_with_interventions` to check that observables defined with parameters change when said parameters are intervened upon. This test fails currently.
> adding failing test for observables defined by parameter values

- pyciemss/compiled_dynamics.py
- tests/test_interfaces.py
Addresses #630 by computing the observables between each interruption and fusing the extended trajectories together, rather than computing observables only after the simulation has completed. This means that every time the observables are computed they use the value of the parameters as they are assigned at that particular moment in time.
This implementation makes heavy use of the existing `LogTrajectory` handler in ChiRho, which is responsible for fusing trajectories together between interruptions.
> Modify observables computations to account for dependence on parameters that change via intervention

- pyciemss/interfaces.py
- tests/test_interfaces.py
This can be used to generate results after running `optimize`.
> Add QoIs as inputs to `sample`

- docs/source/interfaces.ipynb
- docs/source/optimize_interface.ipynb
- pyciemss/interfaces.py
- pyciemss/ouu/ouu.py
- tests/fixtures.py
- tests/test_interfaces.py
`optimize` can now handle fixed interventions on:
- static parameter interventions (already existed)
- static state interventions
- dynamic parameter interventions
- dynamic state interventions
Note that the fixed dynamic interventions might compromise the optimizer's performance so extra care should be taken when using them.
> Added different types of fixed interventions to optimize

- pyciemss/integration_utils/observation.py
Replaced `pandas.DataFrame.applymap` with `.map` to avoid Pandas deprecation warning per @liunelson. Subsumes PR #622.
> changing applymap to map

- docs/source/sample_interface_solvers.ipynb
- pyciemss/compiled_dynamics.py
- pyciemss/integration_utils/intervention_builder.py
Adds a descriptive error message when an `underflow` error is thrown by an adaptive step size solver, or infinite/NaN values are returned for states and/or observables. 
See https://github.com/ciemss/pyciemss/issues/643.
> adding error messages and check for NaN values to compiled_dynamics
